//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi_News_and_Weather.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Weather
    {
        public int id { get; set; }
        public string temp { get; set; }
        public string description { get; set; }
        public string pressure { get; set; }
        public string humidity { get; set; }
        public string speed { get; set; }
        public string deg { get; set; }
        public byte[] visibility { get; set; }
    }
}
