USE [master]
GO
/****** Object:  Database [DataBase]    Script Date: 07/06/2021 9:41:49 a. m. ******/
CREATE DATABASE [DataBase]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DataBase', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\DataBase.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DataBase_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\DataBase_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [DataBase] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DataBase].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [DataBase] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DataBase] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DataBase] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DataBase] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [DataBase] SET ARITHABORT OFF 
GO
ALTER DATABASE [DataBase] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DataBase] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DataBase] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DataBase] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DataBase] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DataBase] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DataBase] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DataBase] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DataBase] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DataBase] SET  DISABLE_BROKER 
GO
ALTER DATABASE [DataBase] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DataBase] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DataBase] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [DataBase] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [DataBase] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DataBase] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [DataBase] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [DataBase] SET RECOVERY FULL 
GO
ALTER DATABASE [DataBase] SET  MULTI_USER 
GO
ALTER DATABASE [DataBase] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [DataBase] SET DB_CHAINING OFF 
GO
ALTER DATABASE [DataBase] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [DataBase] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [DataBase] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [DataBase] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'DataBase', N'ON'
GO
ALTER DATABASE [DataBase] SET QUERY_STORE = OFF
GO
USE [DataBase]
GO
/****** Object:  Table [dbo].[TableCity]    Script Date: 07/06/2021 9:41:50 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TableCity](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[city] [varchar](50) NULL,
	[infor] [varchar](50) NULL,
 CONSTRAINT [PK_city] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TableWebAPI]    Script Date: 07/06/2021 9:41:50 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TableWebAPI](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[author] [varchar](100) NULL,
	[title] [varchar](200) NULL,
	[description] [varchar](300) NULL,
	[url] [varchar](200) NULL,
	[utlToImage] [varchar](200) NULL,
	[publishedAt] [varchar](200) NULL,
	[content_desc] [varchar](500) NULL,
	[description_weather] [varchar](50) NULL,
	[temp] [varchar](50) NULL,
	[pressure] [varchar](50) NULL,
	[humidity] [varchar](50) NULL,
	[visibility] [varchar](50) NULL,
	[speed] [varchar](50) NULL,
	[deg] [varchar](50) NULL,
 CONSTRAINT [PK_TableWebAPI] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[TableCity] ON 
GO
INSERT [dbo].[TableCity] ([id], [city], [infor]) VALUES (1, N'Bogota', N'infor')
GO
INSERT [dbo].[TableCity] ([id], [city], [infor]) VALUES (2, N'London', N'infor')
GO
INSERT [dbo].[TableCity] ([id], [city], [infor]) VALUES (3, N'Bogota', N'infor')
GO
INSERT [dbo].[TableCity] ([id], [city], [infor]) VALUES (4, N'London', N'infor')
GO
SET IDENTITY_INSERT [dbo].[TableCity] OFF
GO
USE [master]
GO
ALTER DATABASE [DataBase] SET  READ_WRITE 
GO
