//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiCity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableWebAPI
    {
        public int id { get; set; }
        public string author { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string url { get; set; }
        public string utlToImage { get; set; }
        public string publishedAt { get; set; }
        public string content_desc { get; set; }
        public string description_weather { get; set; }
        public string temp { get; set; }
        public string pressure { get; set; }
        public string humidity { get; set; }
        public string visibility { get; set; }
        public string speed { get; set; }
        public string deg { get; set; }
    }
}
